"""fix

Revision ID: 1c476b832fc6
Revises: e7c191c770a4
Create Date: 2026-01-03 10:39:54.920612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c476b832fc6'
down_revision: Union[str, None] = 'e7c191c770a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showtimeseat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showtime_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('is_reserved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['seat.id'], ),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtime.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showtimeseat')
    # ### end Alembic commands ###
