"""add status column to showtime table

Revision ID: 5d027b849eb1
Revises: 1c476b832fc6
Create Date: 2026-01-05 13:47:45.629285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d027b849eb1'
down_revision: Union[str, None] = '1c476b832fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtime', sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'FINISHED', 'DRAFT', name='showtimestatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showtime', 'status')
    # ### end Alembic commands ###
