"""add back showtime table

Revision ID: 61d38ea73e97
Revises: 68e20eb7bf44
Create Date: 2025-12-19 22:54:36.986716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d38ea73e97'
down_revision: Union[str, None] = '68e20eb7bf44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ends_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('hall_number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showtime')
    # ### end Alembic commands ###
