"""update showtime

Revision ID: 68e20eb7bf44
Revises: ca4cefe05252
Create Date: 2025-12-19 22:48:57.786526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68e20eb7bf44'
down_revision: Union[str, None] = 'ca4cefe05252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_showtime_movie_id', table_name='showtime')
    op.drop_table('showtime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showtime',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('starts_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ends_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('hall_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='showtime_pkey')
    )
    op.create_index('ix_showtime_movie_id', 'showtime', ['movie_id'], unique=False)
    # ### end Alembic commands ###
